backend:
  name: git-gateway
  branch: master

media_folder: "images"
public_folder: "/images"

collections:
  - name: "productos"
    label: "Productos"
    label_singular: "Producto"
    delete: false
    files:
      - label: "Listado de Productos"
        name: "listado_productos"
        file: "productos.json"
        format: "json"
        fields:
          - label: "Productos"
            name: "productos"
            widget: "list"
            allow_add: true
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Stock", name: "stock", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }
              - { label: "Subcategoría", name: "subcategoria", widget: "string", required: false }
              - label: "Categoría"
                name: "categoria"
                widget: "select"
                options:
                  - { label: "Tapetes Personalizados", value: "tapetes" }
                  - { label: "Impresión 3D", value: "impresion3d" }
                  - { label: "Indumentaria Deportiva", value: "indumentaria" }
                  - { label: "Accesorios", value: "accesorios" }
  - name: "pedidosform"
  label: "Pedidosform"
  folder: "pedidosform"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "Nombre", name: "nombre", widget: "string" }
    - { label: "Teléfono", name: "telefono", widget: "string" }
    - { label: "Ciudad", name: "ciudad", widget: "string" }
    - { label: "Dirección", name: "direccion", widget: "string" }
    - { label: "Productos", name: "carrito", widget: "text" }
    - { label: "Total", name: "total", widget: "string" }
  - name: "pedidos"
    label: "Pedidos"
    label_singular: "Pedido"
    folder: "pedidos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}{{second}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "ID de Pago", name: "payment_id", widget: "string" }
      - { label: "Referencia", name: "reference", widget: "string" }
      - { label: "Correo del comprador", name: "payer_email", widget: "string" }
      - { label: "Método de pago", name: "payment_method", widget: "string" }
      - { label: "Monto total", name: "total", widget: "number" }
      - { label: "Fecha de creación", name: "created_at", widget: "datetime" }
