backend:
  name: git-gateway
  branch: main  # o la rama que uses

media_folder: "images"
public_folder: "/images"

collections:
  - name: "productos"
    label: "Productos"
    label_singular: "Producto"
    folder: "productos.json"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Precio", name: "precio", widget: "number" }
      - { label: "Imagen", name: "imagen", widget: "image" }
